# Generated by Django 3.2.5 on 2021-07-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('artigoNumero', models.CharField(max_length=4, verbose_name='Numero do artigo')),
                ('artigoTexto', models.TextField(verbose_name='Texto do artigo alterado')),
                ('artigoInalterado', models.TextField(verbose_name='Texto do artigo inalterado')),
                ('idCod', models.CharField(max_length=4, verbose_name='id do codigo')),
                ('parte', models.CharField(max_length=1, verbose_name='Artigo dividido Parte')),
                ('infoSuperior', models.CharField(max_length=1000, verbose_name='Informação superior do códio')),
            ],
        ),
    ]
