# Generated by Django 3.2.5 on 2021-07-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_lei', '0002_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
